Repository AntonioK180/react-trello-board, pull requests merged in 2022-04, with the labels that each got.

#13 Feature/home login page
  package-lock.json
  package.json
  public/account_icon.png
  public/trello-icon.gif
  src/App.css
  src/App.js
  src/UserContext.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/index.css
Labels: enhancement

#14 .gitignore file update
  .gitignore
Labels: enhancement

#15 Restructuring/app context
  src/App.js
  src/UserContext.js
  src/components/Homepage/Homepage.js
  src/components/Login/Login.js
  src/structure/json_structure.json
Labels: enhancement

#16 Edit: homepage routing
  src/components/Homepage/Homepage.js
  src/components/Login/Login.js
Labels: enhancement

#18 Feature/8 create many board tables
  package-lock.json
  package.json
  src/App.js
  src/components/Board/Board.css
  src/components/Board/Board.js
  src/components/Column/Column.js
  src/components/CreateBoard/CreateBoard.css
  src/components/CreateBoard/CreateBoard.js
  src/components/Homepage/Homepage.js
  src/components/Login/Login.js
  src/structure/json_structure.json
Labels: enhancement

#19 Feature/single card
  src/App.css
  src/components/Card/Card.js
  src/components/CardAction/CardAction.css
  src/components/CardAction/CardAction.js
  src/components/DateSelector/DateSelector.css
  src/components/DateSelector/DateSelector.js
  src/components/EditCard/EditCard.css
  src/components/EditCard/EditCard.js
  src/components/LabelSelector/LabelSelector.css
  src/components/LabelSelector/LabelSelector.js
  src/components/MembersSelect/MembersSelect.css
  src/components/MembersSelect/MembersSelect.js
Labels: enhancement

#20 Feature/5 create many columns logic
  src/components/Column/Column.css
  src/components/Column/Column.js
Labels: enhancement

#21 Bugfix/add list not dynamic
  src/components/Board/Board.css
  src/components/Board/Board.js
  src/components/Column/Column.js
  src/components/CreateBoard/CreateBoard.css
  src/components/CreateBoard/CreateBoard.js
  src/components/Login/Login.css
  src/components/Login/Login.js
Labels: bug

#22 Feature/board service
  src/components/Board/Board.js
  src/components/CreateBoard/CreateBoard.js
  src/components/Homepage/Homepage.js
  src/services/BoardService.js
Labels: enhancement

#23 Styling/columns cards
  src/App.css
  src/App.js
  src/components/Board/Board.css
  src/components/Board/Board.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Column/Column.css
  src/components/Column/Column.js
  src/components/CreateBoard/CreateBoard.css
  src/components/EditCard/EditCard.css
  src/components/EditCard/EditCard.js
  src/components/Portal/Portal.js
Labels: enhancement

#24 Add: local storage for cards objects
  src/components/Board/Board.js
  src/components/Column/Column.js
Labels: enhancement

#26 Feature/10 search bar
  public/icons8-search-24.png
  src/App.js
  src/components/Board/Board.js
  src/components/Column/Column.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/Login/Login.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
Labels: enhancement

#28 Make search work without button
  src/App.js
  src/components/Homepage/Homepage.js
  src/components/Login/Login.js
  src/components/NavBar/NavBar.js
Labels: enhancement

#32 Add z-indexes to editcard popups.
  src/components/Column/Column.css
  src/components/DateSelector/DateSelector.css
  src/components/LabelSelector/LabelSelector.css
  src/components/MembersSelect/MembersSelect.css
Labels: bug

#34 Feature/12 archive
  public/index.html
  src/App.js
  src/components/Archive/Archive.css
  src/components/Archive/Archive.js
  src/components/Card/Card.js
  src/components/CardAction/CardAction.css
  src/components/Column/Column.js
  src/components/EditCard/EditCard.js
  src/components/Login/Login.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/services/ArchiveService.js
  src/structure/json_structure.json
Labels: enhancement

#37 Added: logout
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
Labels: enhancement

#39 Fixed: Improper user fetching.
  src/components/Login/Login.js
Labels: bug

#41 Bugfix/35 navbar styling
  public/account_icon.png
  public/icons8-search-24.png
  public/trello-icon.gif
  src/components/Card/Card.js
  src/components/CardAction/CardAction.css
  src/components/Column/Column.js
  src/components/EditCard/EditCard.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
Labels: bug, enhancement

#43 Fixed: Search does not work.
  src/App.css
  src/components/NavBar/NavBar.css
Labels: bug

#45 Feature/44 removing permanently cards from columns
  src/components/Archive/Archive.css
  src/components/Archive/Archive.js
  src/services/ArchiveService.js
Labels: enhancement

#46 40 make cards move between columns
  src/components/Board/Board.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Column/Column.js
  src/components/EditCard/EditCard.js
  src/services/BoardService.js
Labels: duplicate, enhancement

#47 Feature/31 crud operations with cards columns boards
  src/components/Card/Card.js
  src/components/Column/Column.js
  src/components/EditCard/EditCard.css
  src/components/EditCard/EditCard.js
  src/services/BoardService.js
Labels: enhancement

#49 EditCard now shows actual description of the card.
  src/components/EditCard/EditCard.js
Labels: enhancement

#50 Feature/boards view
  src/components/Boards/Boards.css
  src/components/Boards/Boards.js
  src/index.css
Labels: enhancement
